spring:
  datasource:
    url: jdbc:oracle:thin:@172.26.2.110:1521/DESAIES
    username: APLITALENTOV3
    password: GtqkFh3845
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true